name: TradingView Scraper A2

on:
  schedule:
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

jobs:
  scrape:
    strategy:
      matrix:
        batch: [0, 1, 2, 3, 4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Create .env
        run: |
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> .env
          echo "SOURCE_SHEET=${{ secrets.SOURCE_SHEET }}" >> .env
          echo "OUTPUT_SHEET_ID=${{ secrets.OUTPUT_SHEET_ID }}" >> .env
          echo "OUTPUT_SHEET=${{ secrets.OUTPUT_SHEET }}" >> .env
          echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}" >> .env
          echo "GOOGLE_PRIVATE_KEY=\"${{ secrets.GOOGLE_PRIVATE_KEY }}\"" >> .env
          echo "ACCOUNT_START=450" >> .env
          echo "ACCOUNT_END=900" >> .env
          echo "BATCH_SIZE=90" >> .env

      - run: echo "${{ secrets.COOKIES_BASE64 }}" | base64 -d > cookies.json

      - run: node index.js ${{ matrix.batch }}
